/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCartaoRouteImport } from './routes/_authenticated/cartao'
import { Route as AuthenticatedComprarRouteImport } from './routes/_authenticated/comprar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFinancasRouteImport } from './routes/_authenticated/financas'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedLojinhaRouteImport } from './routes/_authenticated/lojinha'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedProdutividadeRouteImport } from './routes/_authenticated/produtividade'
import { Route as AuthenticatedRetroativoRouteImport } from './routes/_authenticated/retroativo'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated/alunos.index'
import { Route as AuthenticatedAlunosIdRouteImport } from './routes/_authenticated/alunos.$id'
import { Route as AuthenticatedBolsaIndexRouteImport } from './routes/_authenticated/bolsa.index'
import { Route as AuthenticatedBolsaIdRouteImport } from './routes/_authenticated/bolsa.$id'
import { Route as AuthenticatedDietaIndexRouteImport } from './routes/_authenticated/dieta.index'
import { Route as AuthenticatedDietaCaloriasRouteImport } from './routes/_authenticated/dieta.calorias'
import { Route as AuthenticatedDietaConsistenciaRouteImport } from './routes/_authenticated/dieta.consistencia'
import { Route as AuthenticatedDietaEvolucaoRouteImport } from './routes/_authenticated/dieta.evolucao'
import { Route as AuthenticatedFlashcardsIndexRouteImport } from './routes/_authenticated/flashcards.index'
import { Route as AuthenticatedFlashcardsIdRouteImport } from './routes/_authenticated/flashcards.$id'
import { Route as AuthenticatedHabitosIndexRouteImport } from './routes/_authenticated/habitos.index'
import { Route as AuthenticatedHabitosIdRouteImport } from './routes/_authenticated/habitos.$id'
import { Route as AuthenticatedTreinoIndexRouteImport } from './routes/_authenticated/treino.index'
import { Route as AuthenticatedTreinoIdRouteImport } from './routes/_authenticated/treino.$id'
import { Route as AuthenticatedTreinoExerciciosRouteImport } from './routes/_authenticated/treino.exercicios'
import { Route as AuthenticatedViolaoIndexRouteImport } from './routes/_authenticated/violao.index'
import { Route as AuthenticatedViolaoIdRouteImport } from './routes/_authenticated/violao.$id'
import { Route as AuthenticatedViolaoAcordesRouteImport } from './routes/_authenticated/violao.acordes'
import { Route as ApiPublicSiriEventsRouteImport } from './routes/api/public/siri/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartaoRoute = AuthenticatedCartaoRouteImport.update({
  id: '/cartao',
  path: '/cartao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprarRoute = AuthenticatedComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancasRoute = AuthenticatedFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojinhaRoute = AuthenticatedLojinhaRouteImport.update({
  id: '/lojinha',
  path: '/lojinha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutividadeRoute =
  AuthenticatedProdutividadeRouteImport.update({
    id: '/produtividade',
    path: '/produtividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRetroativoRoute = AuthenticatedRetroativoRouteImport.update({
  id: '/retroativo',
  path: '/retroativo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlunosIdRoute = AuthenticatedAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBolsaIndexRoute = AuthenticatedBolsaIndexRouteImport.update({
  id: '/bolsa/',
  path: '/bolsa/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBolsaIdRoute = AuthenticatedBolsaIdRouteImport.update({
  id: '/bolsa/$id',
  path: '/bolsa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietaIndexRoute = AuthenticatedDietaIndexRouteImport.update({
  id: '/dieta/',
  path: '/dieta/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietaCaloriasRoute =
  AuthenticatedDietaCaloriasRouteImport.update({
    id: '/dieta/calorias',
    path: '/dieta/calorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDietaConsistenciaRoute =
  AuthenticatedDietaConsistenciaRouteImport.update({
    id: '/dieta/consistencia',
    path: '/dieta/consistencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDietaEvolucaoRoute =
  AuthenticatedDietaEvolucaoRouteImport.update({
    id: '/dieta/evolucao',
    path: '/dieta/evolucao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlashcardsIndexRoute =
  AuthenticatedFlashcardsIndexRouteImport.update({
    id: '/flashcards/',
    path: '/flashcards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlashcardsIdRoute =
  AuthenticatedFlashcardsIdRouteImport.update({
    id: '/flashcards/$id',
    path: '/flashcards/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabitosIndexRoute =
  AuthenticatedHabitosIndexRouteImport.update({
    id: '/habitos/',
    path: '/habitos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabitosIdRoute = AuthenticatedHabitosIdRouteImport.update({
  id: '/habitos/$id',
  path: '/habitos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinoIndexRoute =
  AuthenticatedTreinoIndexRouteImport.update({
    id: '/treino/',
    path: '/treino/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinoIdRoute = AuthenticatedTreinoIdRouteImport.update({
  id: '/treino/$id',
  path: '/treino/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinoExerciciosRoute =
  AuthenticatedTreinoExerciciosRouteImport.update({
    id: '/treino/exercicios',
    path: '/treino/exercicios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViolaoIndexRoute =
  AuthenticatedViolaoIndexRouteImport.update({
    id: '/violao/',
    path: '/violao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViolaoIdRoute = AuthenticatedViolaoIdRouteImport.update({
  id: '/violao/$id',
  path: '/violao/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViolaoAcordesRoute =
  AuthenticatedViolaoAcordesRouteImport.update({
    id: '/violao/acordes',
    path: '/violao/acordes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSiriEventsRoute = ApiPublicSiriEventsRouteImport.update({
  id: '/api/public/siri/events',
  path: '/api/public/siri/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cartao': typeof AuthenticatedCartaoRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financas': typeof AuthenticatedFinancasRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/lojinha': typeof AuthenticatedLojinhaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/retroativo': typeof AuthenticatedRetroativoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/bolsa/$id': typeof AuthenticatedBolsaIdRoute
  '/dieta/calorias': typeof AuthenticatedDietaCaloriasRoute
  '/dieta/consistencia': typeof AuthenticatedDietaConsistenciaRoute
  '/dieta/evolucao': typeof AuthenticatedDietaEvolucaoRoute
  '/flashcards/$id': typeof AuthenticatedFlashcardsIdRoute
  '/habitos/$id': typeof AuthenticatedHabitosIdRoute
  '/treino/$id': typeof AuthenticatedTreinoIdRoute
  '/treino/exercicios': typeof AuthenticatedTreinoExerciciosRoute
  '/violao/$id': typeof AuthenticatedViolaoIdRoute
  '/violao/acordes': typeof AuthenticatedViolaoAcordesRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/bolsa/': typeof AuthenticatedBolsaIndexRoute
  '/dieta/': typeof AuthenticatedDietaIndexRoute
  '/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/habitos/': typeof AuthenticatedHabitosIndexRoute
  '/treino/': typeof AuthenticatedTreinoIndexRoute
  '/violao/': typeof AuthenticatedViolaoIndexRoute
  '/api/public/siri/events': typeof ApiPublicSiriEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cartao': typeof AuthenticatedCartaoRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financas': typeof AuthenticatedFinancasRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/lojinha': typeof AuthenticatedLojinhaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/retroativo': typeof AuthenticatedRetroativoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/bolsa/$id': typeof AuthenticatedBolsaIdRoute
  '/dieta/calorias': typeof AuthenticatedDietaCaloriasRoute
  '/dieta/consistencia': typeof AuthenticatedDietaConsistenciaRoute
  '/dieta/evolucao': typeof AuthenticatedDietaEvolucaoRoute
  '/flashcards/$id': typeof AuthenticatedFlashcardsIdRoute
  '/habitos/$id': typeof AuthenticatedHabitosIdRoute
  '/treino/$id': typeof AuthenticatedTreinoIdRoute
  '/treino/exercicios': typeof AuthenticatedTreinoExerciciosRoute
  '/violao/$id': typeof AuthenticatedViolaoIdRoute
  '/violao/acordes': typeof AuthenticatedViolaoAcordesRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/bolsa': typeof AuthenticatedBolsaIndexRoute
  '/dieta': typeof AuthenticatedDietaIndexRoute
  '/flashcards': typeof AuthenticatedFlashcardsIndexRoute
  '/habitos': typeof AuthenticatedHabitosIndexRoute
  '/treino': typeof AuthenticatedTreinoIndexRoute
  '/violao': typeof AuthenticatedViolaoIndexRoute
  '/api/public/siri/events': typeof ApiPublicSiriEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/cartao': typeof AuthenticatedCartaoRoute
  '/_authenticated/comprar': typeof AuthenticatedComprarRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/financas': typeof AuthenticatedFinancasRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/lojinha': typeof AuthenticatedLojinhaRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/produtividade': typeof AuthenticatedProdutividadeRoute
  '/_authenticated/retroativo': typeof AuthenticatedRetroativoRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/_authenticated/bolsa/$id': typeof AuthenticatedBolsaIdRoute
  '/_authenticated/dieta/calorias': typeof AuthenticatedDietaCaloriasRoute
  '/_authenticated/dieta/consistencia': typeof AuthenticatedDietaConsistenciaRoute
  '/_authenticated/dieta/evolucao': typeof AuthenticatedDietaEvolucaoRoute
  '/_authenticated/flashcards/$id': typeof AuthenticatedFlashcardsIdRoute
  '/_authenticated/habitos/$id': typeof AuthenticatedHabitosIdRoute
  '/_authenticated/treino/$id': typeof AuthenticatedTreinoIdRoute
  '/_authenticated/treino/exercicios': typeof AuthenticatedTreinoExerciciosRoute
  '/_authenticated/violao/$id': typeof AuthenticatedViolaoIdRoute
  '/_authenticated/violao/acordes': typeof AuthenticatedViolaoAcordesRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/bolsa/': typeof AuthenticatedBolsaIndexRoute
  '/_authenticated/dieta/': typeof AuthenticatedDietaIndexRoute
  '/_authenticated/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/_authenticated/habitos/': typeof AuthenticatedHabitosIndexRoute
  '/_authenticated/treino/': typeof AuthenticatedTreinoIndexRoute
  '/_authenticated/violao/': typeof AuthenticatedViolaoIndexRoute
  '/api/public/siri/events': typeof ApiPublicSiriEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/offline'
    | '/redefinir-senha'
    | '/calendario'
    | '/cartao'
    | '/comprar'
    | '/configuracoes'
    | '/financas'
    | '/hoje'
    | '/insights'
    | '/lojinha'
    | '/metas'
    | '/produtividade'
    | '/retroativo'
    | '/tarefas'
    | '/alunos/$id'
    | '/bolsa/$id'
    | '/dieta/calorias'
    | '/dieta/consistencia'
    | '/dieta/evolucao'
    | '/flashcards/$id'
    | '/habitos/$id'
    | '/treino/$id'
    | '/treino/exercicios'
    | '/violao/$id'
    | '/violao/acordes'
    | '/alunos/'
    | '/bolsa/'
    | '/dieta/'
    | '/flashcards/'
    | '/habitos/'
    | '/treino/'
    | '/violao/'
    | '/api/public/siri/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/offline'
    | '/redefinir-senha'
    | '/calendario'
    | '/cartao'
    | '/comprar'
    | '/configuracoes'
    | '/financas'
    | '/hoje'
    | '/insights'
    | '/lojinha'
    | '/metas'
    | '/produtividade'
    | '/retroativo'
    | '/tarefas'
    | '/alunos/$id'
    | '/bolsa/$id'
    | '/dieta/calorias'
    | '/dieta/consistencia'
    | '/dieta/evolucao'
    | '/flashcards/$id'
    | '/habitos/$id'
    | '/treino/$id'
    | '/treino/exercicios'
    | '/violao/$id'
    | '/violao/acordes'
    | '/alunos'
    | '/bolsa'
    | '/dieta'
    | '/flashcards'
    | '/habitos'
    | '/treino'
    | '/violao'
    | '/api/public/siri/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/offline'
    | '/redefinir-senha'
    | '/_authenticated/calendario'
    | '/_authenticated/cartao'
    | '/_authenticated/comprar'
    | '/_authenticated/configuracoes'
    | '/_authenticated/financas'
    | '/_authenticated/hoje'
    | '/_authenticated/insights'
    | '/_authenticated/lojinha'
    | '/_authenticated/metas'
    | '/_authenticated/produtividade'
    | '/_authenticated/retroativo'
    | '/_authenticated/tarefas'
    | '/_authenticated/alunos/$id'
    | '/_authenticated/bolsa/$id'
    | '/_authenticated/dieta/calorias'
    | '/_authenticated/dieta/consistencia'
    | '/_authenticated/dieta/evolucao'
    | '/_authenticated/flashcards/$id'
    | '/_authenticated/habitos/$id'
    | '/_authenticated/treino/$id'
    | '/_authenticated/treino/exercicios'
    | '/_authenticated/violao/$id'
    | '/_authenticated/violao/acordes'
    | '/_authenticated/alunos/'
    | '/_authenticated/bolsa/'
    | '/_authenticated/dieta/'
    | '/_authenticated/flashcards/'
    | '/_authenticated/habitos/'
    | '/_authenticated/treino/'
    | '/_authenticated/violao/'
    | '/api/public/siri/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OfflineRoute: typeof OfflineRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiPublicSiriEventsRoute: typeof ApiPublicSiriEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartao': {
      id: '/_authenticated/cartao'
      path: '/cartao'
      fullPath: '/cartao'
      preLoaderRoute: typeof AuthenticatedCartaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comprar': {
      id: '/_authenticated/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof AuthenticatedComprarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financas': {
      id: '/_authenticated/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof AuthenticatedFinancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojinha': {
      id: '/_authenticated/lojinha'
      path: '/lojinha'
      fullPath: '/lojinha'
      preLoaderRoute: typeof AuthenticatedLojinhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtividade': {
      id: '/_authenticated/produtividade'
      path: '/produtividade'
      fullPath: '/produtividade'
      preLoaderRoute: typeof AuthenticatedProdutividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retroativo': {
      id: '/_authenticated/retroativo'
      path: '/retroativo'
      fullPath: '/retroativo'
      preLoaderRoute: typeof AuthenticatedRetroativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/$id': {
      id: '/_authenticated/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bolsa/': {
      id: '/_authenticated/bolsa/'
      path: '/bolsa'
      fullPath: '/bolsa/'
      preLoaderRoute: typeof AuthenticatedBolsaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bolsa/$id': {
      id: '/_authenticated/bolsa/$id'
      path: '/bolsa/$id'
      fullPath: '/bolsa/$id'
      preLoaderRoute: typeof AuthenticatedBolsaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta/': {
      id: '/_authenticated/dieta/'
      path: '/dieta'
      fullPath: '/dieta/'
      preLoaderRoute: typeof AuthenticatedDietaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta/calorias': {
      id: '/_authenticated/dieta/calorias'
      path: '/dieta/calorias'
      fullPath: '/dieta/calorias'
      preLoaderRoute: typeof AuthenticatedDietaCaloriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta/consistencia': {
      id: '/_authenticated/dieta/consistencia'
      path: '/dieta/consistencia'
      fullPath: '/dieta/consistencia'
      preLoaderRoute: typeof AuthenticatedDietaConsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta/evolucao': {
      id: '/_authenticated/dieta/evolucao'
      path: '/dieta/evolucao'
      fullPath: '/dieta/evolucao'
      preLoaderRoute: typeof AuthenticatedDietaEvolucaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards/': {
      id: '/_authenticated/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AuthenticatedFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards/$id': {
      id: '/_authenticated/flashcards/$id'
      path: '/flashcards/$id'
      fullPath: '/flashcards/$id'
      preLoaderRoute: typeof AuthenticatedFlashcardsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos/': {
      id: '/_authenticated/habitos/'
      path: '/habitos'
      fullPath: '/habitos/'
      preLoaderRoute: typeof AuthenticatedHabitosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos/$id': {
      id: '/_authenticated/habitos/$id'
      path: '/habitos/$id'
      fullPath: '/habitos/$id'
      preLoaderRoute: typeof AuthenticatedHabitosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treino/': {
      id: '/_authenticated/treino/'
      path: '/treino'
      fullPath: '/treino/'
      preLoaderRoute: typeof AuthenticatedTreinoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treino/$id': {
      id: '/_authenticated/treino/$id'
      path: '/treino/$id'
      fullPath: '/treino/$id'
      preLoaderRoute: typeof AuthenticatedTreinoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treino/exercicios': {
      id: '/_authenticated/treino/exercicios'
      path: '/treino/exercicios'
      fullPath: '/treino/exercicios'
      preLoaderRoute: typeof AuthenticatedTreinoExerciciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/violao/': {
      id: '/_authenticated/violao/'
      path: '/violao'
      fullPath: '/violao/'
      preLoaderRoute: typeof AuthenticatedViolaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/violao/$id': {
      id: '/_authenticated/violao/$id'
      path: '/violao/$id'
      fullPath: '/violao/$id'
      preLoaderRoute: typeof AuthenticatedViolaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/violao/acordes': {
      id: '/_authenticated/violao/acordes'
      path: '/violao/acordes'
      fullPath: '/violao/acordes'
      preLoaderRoute: typeof AuthenticatedViolaoAcordesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/siri/events': {
      id: '/api/public/siri/events'
      path: '/api/public/siri/events'
      fullPath: '/api/public/siri/events'
      preLoaderRoute: typeof ApiPublicSiriEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCartaoRoute: typeof AuthenticatedCartaoRoute
  AuthenticatedComprarRoute: typeof AuthenticatedComprarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFinancasRoute: typeof AuthenticatedFinancasRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedLojinhaRoute: typeof AuthenticatedLojinhaRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedProdutividadeRoute: typeof AuthenticatedProdutividadeRoute
  AuthenticatedRetroativoRoute: typeof AuthenticatedRetroativoRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedAlunosIdRoute: typeof AuthenticatedAlunosIdRoute
  AuthenticatedBolsaIdRoute: typeof AuthenticatedBolsaIdRoute
  AuthenticatedDietaCaloriasRoute: typeof AuthenticatedDietaCaloriasRoute
  AuthenticatedDietaConsistenciaRoute: typeof AuthenticatedDietaConsistenciaRoute
  AuthenticatedDietaEvolucaoRoute: typeof AuthenticatedDietaEvolucaoRoute
  AuthenticatedFlashcardsIdRoute: typeof AuthenticatedFlashcardsIdRoute
  AuthenticatedHabitosIdRoute: typeof AuthenticatedHabitosIdRoute
  AuthenticatedTreinoIdRoute: typeof AuthenticatedTreinoIdRoute
  AuthenticatedTreinoExerciciosRoute: typeof AuthenticatedTreinoExerciciosRoute
  AuthenticatedViolaoIdRoute: typeof AuthenticatedViolaoIdRoute
  AuthenticatedViolaoAcordesRoute: typeof AuthenticatedViolaoAcordesRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedBolsaIndexRoute: typeof AuthenticatedBolsaIndexRoute
  AuthenticatedDietaIndexRoute: typeof AuthenticatedDietaIndexRoute
  AuthenticatedFlashcardsIndexRoute: typeof AuthenticatedFlashcardsIndexRoute
  AuthenticatedHabitosIndexRoute: typeof AuthenticatedHabitosIndexRoute
  AuthenticatedTreinoIndexRoute: typeof AuthenticatedTreinoIndexRoute
  AuthenticatedViolaoIndexRoute: typeof AuthenticatedViolaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCartaoRoute: AuthenticatedCartaoRoute,
  AuthenticatedComprarRoute: AuthenticatedComprarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFinancasRoute: AuthenticatedFinancasRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedLojinhaRoute: AuthenticatedLojinhaRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedProdutividadeRoute: AuthenticatedProdutividadeRoute,
  AuthenticatedRetroativoRoute: AuthenticatedRetroativoRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedAlunosIdRoute: AuthenticatedAlunosIdRoute,
  AuthenticatedBolsaIdRoute: AuthenticatedBolsaIdRoute,
  AuthenticatedDietaCaloriasRoute: AuthenticatedDietaCaloriasRoute,
  AuthenticatedDietaConsistenciaRoute: AuthenticatedDietaConsistenciaRoute,
  AuthenticatedDietaEvolucaoRoute: AuthenticatedDietaEvolucaoRoute,
  AuthenticatedFlashcardsIdRoute: AuthenticatedFlashcardsIdRoute,
  AuthenticatedHabitosIdRoute: AuthenticatedHabitosIdRoute,
  AuthenticatedTreinoIdRoute: AuthenticatedTreinoIdRoute,
  AuthenticatedTreinoExerciciosRoute: AuthenticatedTreinoExerciciosRoute,
  AuthenticatedViolaoIdRoute: AuthenticatedViolaoIdRoute,
  AuthenticatedViolaoAcordesRoute: AuthenticatedViolaoAcordesRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedBolsaIndexRoute: AuthenticatedBolsaIndexRoute,
  AuthenticatedDietaIndexRoute: AuthenticatedDietaIndexRoute,
  AuthenticatedFlashcardsIndexRoute: AuthenticatedFlashcardsIndexRoute,
  AuthenticatedHabitosIndexRoute: AuthenticatedHabitosIndexRoute,
  AuthenticatedTreinoIndexRoute: AuthenticatedTreinoIndexRoute,
  AuthenticatedViolaoIndexRoute: AuthenticatedViolaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OfflineRoute: OfflineRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiPublicSiriEventsRoute: ApiPublicSiriEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
